import json

notebook_path = "/home/ziyad/Dev/PFA/Training/train_rf.ipynb"
with open(notebook_path, "r") as f:
    nb = json.load(f)

# Cell 1: Add new imports
nb["cells"][1]["source"] = [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import mlflow\n",
    "import mlflow.sklearn\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.base import BaseEstimator, TransformerMixin\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.preprocessing import OneHotEncoder, TargetEncoder\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report, precision_recall_curve\n",
    "from imblearn.over_sampling import SMOTE\n",
    "from imblearn.pipeline import Pipeline as ImbPipeline\n",
    "from utility.main import read_data\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
]

# Cell 3: CustomMapper (drop near-zeros)
nb["cells"][3]["source"] = [
    "class CustomMapper(BaseEstimator, TransformerMixin):\n",
    "    def __init__(self):\n",
    "        pass\n",
    "        \n",
    "    def fit(self, X, y=None):\n",
    "        return self\n",
    "        \n",
    "    def transform(self, X):\n",
    "        X_copy = X.copy()\n",
    "        \n",
    "        # 1. Age Mapping\n",
    "        age_map = {\n",
    "            '[0-10)': 0, '[10-20)': 1, '[20-30)': 2, '[30-40)': 3, \n",
    "            '[40-50)': 4, '[50-60)': 5, '[60-70)': 6, '[70-80)': 7, \n",
    "            '[80-90)': 8, '[90-100)': 9\n",
    "        }\n",
    "        if 'age' in X_copy.columns:\n",
    "            X_copy['age'] = X_copy['age'].replace(age_map)\n",
    "            \n",
    "        # 2. Binary Mappings\n",
    "        if 'change' in X_copy.columns:\n",
    "            X_copy['change'] = X_copy['change'].replace({'No': 0, 'Ch': 1}).astype(float)\n",
    "        if 'diabetesMed' in X_copy.columns:\n",
    "            X_copy['diabetesMed'] = X_copy['diabetesMed'].replace({'No': 0, 'Yes': 1}).astype(float)\n",
    "        if 'gender' in X_copy.columns:\n",
    "            X_copy['gender'] = X_copy['gender'].replace({'Male': 0, 'Female': 1}).astype(float)\n",
    "            \n",
    "        # 3. Constant columns dropping + near zero variance\n",
    "        constant_cols = ['citoglipton', 'metformin-rosiglitazone', 'examide', 'acetohexamide', 'troglitazone', 'glimepiride-pioglitazone']\n",
    "        X_copy = X_copy.drop(columns=constant_cols, errors='ignore')\n",
    "                \n",
    "        return X_copy"
]

# Cell 4: Pipeline columns
nb["cells"][4]["source"] = [
    "# Separate features and target\n",
    "X = df.drop(columns=['target'])\n",
    "y = df['target']\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
    "\n",
    "# Grouping columns for specific transformations\n",
    "num_cols = [\n",
    "    'time_in_hospital', 'num_lab_procedures', 'num_procedures', \n",
    "    'num_medications', 'number_outpatient', 'number_emergency', \n",
    "    'number_inpatient', 'number_diagnoses'\n",
    "]\n",
    "diag_cols = ['diag_1', 'diag_2', 'diag_3']\n",
    "medication_cols = [\n",
    "    'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', \n",
    "    'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', \n",
    "    'rosiglitazone', 'acarbose', 'miglitol', 'tolazamide', \n",
    "    'insulin', 'glyburide-metformin', 'glipizide-metformin', \n",
    "    'metformin-pioglitazone'\n",
    "]\n",
    "constant_cols = ['citoglipton', 'metformin-rosiglitazone', 'examide', 'acetohexamide', 'troglitazone', 'glimepiride-pioglitazone']\n",
    "active_medication_cols = [col for col in medication_cols if col not in constant_cols]\n",
    "# Add medication columns to cat_cols so they go through OneHotEncoder\n",
    "cat_cols = ['race', 'max_glu_serum', 'A1Cresult'] + active_medication_cols\n",
    "\n",
    "numerical_transformer = SimpleImputer(strategy='mean')\n",
    "categorical_transformer = Pipeline(steps=[\n",
    "    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),\n",
    "    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))\n",
    "])\n",
    "\n",
    "# Target Encoder handles diagnoses columns\n",
    "# Note: smoothing mitigates data-leakage / overfitting\n",
    "target_encoder_transformer = TargetEncoder(smooth='auto')\n",
    "\n",
    "col_transformer = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', numerical_transformer, num_cols),\n",
    "        ('cat', categorical_transformer, cat_cols),\n",
    "        ('diag_target_enc', target_encoder_transformer, diag_cols)\n",
    "    ],\n",
    "    remainder='passthrough'  # Keep transformed age, gender from CustomMapper\n",
    ")\n",
    "\n",
    "preprocessor = Pipeline(steps=[\n",
    "    ('custom_mapper', CustomMapper()),\n",
    "    ('col_transform', col_transformer)\n",
    "])\n",
    "\n",
    "# Preview pipeline components\n",
    "preprocessor"
]

# Cell 5: Model training and reporting (ImbPipeline, SMOTE, class_weight='balanced', thresholding, weighted F1)
nb["cells"][5]["source"] = [
    "# Setup MLflow Tracking\n",
    "mlflow.set_tracking_uri(\"http://127.0.0.1:5000\")\n",
    "mlflow.set_experiment(\"Diabetic_Readmission\")\n",
    "\n",
    "with mlflow.start_run(run_name=\"Random_Forest_Pipeline\"):\n",
    "    # Define Model - Fix: use class_weight='balanced'\n",
    "    model = RandomForestClassifier(\n",
    "        n_estimators=200, \n",
    "        max_depth=12, \n",
    "        min_samples_leaf=5, \n",
    "        class_weight='balanced', \n",
    "        random_state=42\n",
    "    )\n",
    "    \n",
    "    # Full classification pipeline using ImbPipeline to support SMOTE\n",
    "    # Fix: use SMOTE\n",
    "    full_pipeline = ImbPipeline(steps=[\n",
    "        ('preprocessor', preprocessor),\n",
    "        ('smote', SMOTE(random_state=42)),\n",
    "        ('classifier', model)\n",
    "    ])\n",
    "    \n",
    "    print(\"Training Pipeline Configured. Fitting model...\")\n",
    "    full_pipeline.fit(X_train, y_train)\n",
    "    \n",
    "    print(\"Evaluating Model...\")\n",
    "    y_proba = full_pipeline.predict_proba(X_test)[:, 1]\n",
    "    \n",
    "    # Fix: Threshold tuning\n",
    "    precisions, recalls, thresholds = precision_recall_curve(y_test, y_proba)\n",
    "    f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-10)\n",
    "    best_threshold = thresholds[np.argmax(f1_scores[:-1])]\n",
    "    print(f\"Optimal Threshold: {best_threshold:.4f}\")\n",
    "    \n",
    "    y_pred = (y_proba >= best_threshold).astype(int)\n",
    "    \n",
    "    acc = accuracy_score(y_test, y_pred)\n",
    "    # Fix: Use weighted and macro averages for better context\n",
    "    f1_binary = f1_score(y_test, y_pred)\n",
    "    f1_weighted = f1_score(y_test, y_pred, average='weighted')\n",
    "    f1_macro = f1_score(y_test, y_pred, average='macro')\n",
    "    roc_auc = roc_auc_score(y_test, y_proba)\n",
    "    \n",
    "    print(f\"Accuracy: {acc:.4f}\")\n",
    "    print(f\"F1 Score (Binary): {f1_binary:.4f}\")\n",
    "    print(f\"F1 Score (Weighted): {f1_weighted:.4f}\")\n",
    "    print(f\"F1 Score (Macro): {f1_macro:.4f}\")\n",
    "    print(f\"ROC-AUC: {roc_auc:.4f}\")\n",
    "    print(\"\\nClassification Report:\\n\", classification_report(y_test, y_pred))\n",
    "    \n",
    "    # Logging to MLflow\n",
    "    mlflow.log_param(\"model_type\", \"Random Forest with SMOTE\")\n",
    "    mlflow.log_params(model.get_params())\n",
    "    mlflow.log_param(\"optimal_threshold\", best_threshold)\n",
    "    \n",
    "    mlflow.log_metric(\"accuracy\", acc)\n",
    "    mlflow.log_metric(\"f1_score_binary\", f1_binary)\n",
    "    mlflow.log_metric(\"f1_score_weighted\", f1_weighted)\n",
    "    mlflow.log_metric(\"f1_score_macro\", f1_macro)\n",
    "    mlflow.log_metric(\"roc_auc\", roc_auc)\n",
    "    \n",
    "    # Log the complete pipeline\n",
    "    mlflow.sklearn.log_model(full_pipeline, \"model\", serialization_format=\"cloudpickle\")\n",
    "    \n",
    "    print(\"Logging to MLflow complete!\")\n"
]

for cell in nb["cells"]:
    if "outputs" in cell:
        cell["outputs"] = []

with open(notebook_path, "w") as f:
    json.dump(nb, f, indent=1)

print("success")
