import json

notebook_path = "/home/ziyad/Dev/PFA/Training/train_rf.ipynb"
with open(notebook_path, "r") as f:
    nb = json.load(f)

# Cell 3 modification (CustomMapper)
nb["cells"][3]["source"] = [
    "class CustomMapper(BaseEstimator, TransformerMixin):\n",
    "    def __init__(self):\n",
    "        pass\n",
    "        \n",
    "    def fit(self, X, y=None):\n",
    "        return self\n",
    "        \n",
    "    def transform(self, X):\n",
    "        X_copy = X.copy()\n",
    "        \n",
    "        # 1. Age Mapping\n",
    "        age_map = {\n",
    "            '[0-10)': 0, '[10-20)': 1, '[20-30)': 2, '[30-40)': 3, \n",
    "            '[40-50)': 4, '[50-60)': 5, '[60-70)': 6, '[70-80)': 7, \n",
    "            '[80-90)': 8, '[90-100)': 9\n",
    "        }\n",
    "        if 'age' in X_copy.columns:\n",
    "            X_copy['age'] = X_copy['age'].replace(age_map)\n",
    "            \n",
    "        # 2. Binary Mappings\n",
    "        if 'change' in X_copy.columns:\n",
    "            X_copy['change'] = X_copy['change'].replace({'No': 0, 'Ch': 1}).astype(float)\n",
    "        if 'diabetesMed' in X_copy.columns:\n",
    "            X_copy['diabetesMed'] = X_copy['diabetesMed'].replace({'No': 0, 'Yes': 1}).astype(float)\n",
    "        if 'gender' in X_copy.columns:\n",
    "            X_copy['gender'] = X_copy['gender'].replace({'Male': 0, 'Female': 1}).astype(float)\n",
    "            \n",
    "        # 3. Constant columns dropping\n",
    "        constant_cols = ['citoglipton', 'metformin-rosiglitazone', 'examide']\n",
    "        X_copy = X_copy.drop(columns=constant_cols, errors='ignore')\n",
    "                \n",
    "        return X_copy"
]

# Cell 4 modification (Pipeline columns)
nb["cells"][4]["source"] = [
    "# Separate features and target\n",
    "X = df.drop(columns=['target'])\n",
    "y = df['target']\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
    "\n",
    "# Grouping columns for specific transformations\n",
    "num_cols = [\n",
    "    'time_in_hospital', 'num_lab_procedures', 'num_procedures', \n",
    "    'num_medications', 'number_outpatient', 'number_emergency', \n",
    "    'number_inpatient', 'number_diagnoses'\n",
    "]\n",
    "diag_cols = ['diag_1', 'diag_2', 'diag_3']\n",
    "medication_cols = [\n",
    "    'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', \n",
    "    'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', \n",
    "    'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', \n",
    "    'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', \n",
    "    'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone'\n",
    "]\n",
    "constant_cols = ['citoglipton', 'metformin-rosiglitazone', 'examide']\n",
    "active_medication_cols = [col for col in medication_cols if col not in constant_cols]\n",
    "# Add medication columns to cat_cols so they go through OneHotEncoder\n",
    "cat_cols = ['race', 'max_glu_serum', 'A1Cresult'] + active_medication_cols\n",
    "\n",
    "numerical_transformer = SimpleImputer(strategy='mean')\n",
    "categorical_transformer = Pipeline(steps=[\n",
    "    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),\n",
    "    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))\n",
    "])\n",
    "\n",
    "# Target Encoder handles diagnoses columns\n",
    "# Note: smoothing mitigates data-leakage / overfitting\n",
    "target_encoder_transformer = TargetEncoder(smooth='auto')\n",
    "\n",
    "col_transformer = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', numerical_transformer, num_cols),\n",
    "        ('cat', categorical_transformer, cat_cols),\n",
    "        ('diag_target_enc', target_encoder_transformer, diag_cols)\n",
    "    ],\n",
    "    remainder='passthrough'  # Keep transformed age, gender from CustomMapper\n",
    ")\n",
    "\n",
    "preprocessor = Pipeline(steps=[\n",
    "    ('custom_mapper', CustomMapper()),\n",
    "    ('col_transform', col_transformer)\n",
    "])\n",
    "\n",
    "# Preview pipeline components\n",
    "preprocessor"
]

# Cell 5 modification (RF Hyperparameters)
nb["cells"][5]["source"] = [
    "# Setup MLflow Tracking\n",
    "mlflow.set_tracking_uri(\"http://127.0.0.1:5000\")\n",
    "mlflow.set_experiment(\"Diabetic_Readmission\")\n",
    "\n",
    "with mlflow.start_run(run_name=\"Random_Forest_Pipeline\"):\n",
    "    # Define Model\n",
    "    model = RandomForestClassifier(\n",
    "        n_estimators=200, \n",
    "        max_depth=12, \n",
    "        min_samples_leaf=5, \n",
    "        class_weight='balanced_subsample', \n",
    "        random_state=42\n",
    "    )\n",
    "    \n",
    "    # Full classification pipeline\n",
    "    full_pipeline = Pipeline(steps=[\n",
    "        ('preprocessor', preprocessor),\n",
    "        ('classifier', model)\n",
    "    ])\n",
    "    \n",
    "    print(\"Training Pipeline Configured. Fitting model...\")\n",
    "    full_pipeline.fit(X_train, y_train)\n",
    "    \n",
    "    print(\"Evaluating Model...\")\n",
    "    y_pred = full_pipeline.predict(X_test)\n",
    "    y_proba = full_pipeline.predict_proba(X_test)[:, 1]\n",
    "    \n",
    "    acc = accuracy_score(y_test, y_pred)\n",
    "    f1 = f1_score(y_test, y_pred)\n",
    "    roc_auc = roc_auc_score(y_test, y_proba)\n",
    "    \n",
    "    print(f\"Accuracy: {acc:.4f}\")\n",
    "    print(f\"F1 Score: {f1:.4f}\")\n",
    "    print(f\"ROC-AUC: {roc_auc:.4f}\")\n",
    "    print(\"\\nClassification Report:\\n\", classification_report(y_test, y_pred))\n",
    "    \n",
    "    # Logging to MLflow\n",
    "    mlflow.log_param(\"model_type\", \"Random Forest\")\n",
    "    mlflow.log_params(model.get_params())\n",
    "    \n",
    "    mlflow.log_metric(\"accuracy\", acc)\n",
    "    mlflow.log_metric(\"f1_score\", f1)\n",
    "    mlflow.log_metric(\"roc_auc\", roc_auc)\n",
    "    \n",
    "    # Log the complete scikit-learn pipeline\n",
    "    mlflow.sklearn.log_model(full_pipeline, \"model\", serialization_format=\"cloudpickle\")\n",
    "    \n",
    "    print(\"Logging to MLflow complete!\")"
]

with open(notebook_path, "w") as f:
    json.dump(nb, f, indent=1)

print("success")
